# Generated by Django 6.1 on 2026-08-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartnemt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('square_meters', models.FloatField(verbose_name='Площадь (кв.м.)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartments/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='apartnemt.amenity', verbose_name='Удобства')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='apartnemt.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
