# Generated by Django 6.1 on 2026-08-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartnemt', '0002_apartment_delete_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
    ]
