# Generated by Django 6.1 on 2026-09-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartnemt', '0003_remove_apartment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='balcony_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество балконов / лоджий'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('shared', 'Совмещенный'), ('separate', 'Раздельный'), ('multiple', 'Несколько')], max_length=20, null=True, verbose_name='Санузел'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='build_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building_type',
            field=models.CharField(blank=True, choices=[('new', 'Новостройка'), ('resale', 'Вторичка')], max_length=20, null=True, verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолков (м)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('sale', 'Продажа'), ('long_rent', 'Долгосрочная аренда'), ('daily_rent', 'Посуточная аренда')], max_length=20, null=True, verbose_name='Тип сделки'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Залог / Депозит'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='elevator',
            field=models.CharField(blank=True, choices=[('passenger', 'Пассажирский'), ('cargo', 'Грузовой'), ('both', 'Пассажирский и грузовой'), ('none', 'Нет лифта')], default='none', max_length=20, null=True, verbose_name='Наличие лифта'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/', verbose_name='Планировка'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen_square_meters',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь кухни (кв.м.)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='living_square_meters',
            field=models.FloatField(blank=True, null=True, verbose_name='Жилая площадь (кв.м.)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='negotiable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Возможен торг'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='parking',
            field=models.CharField(blank=True, choices=[('ground', 'Наземная'), ('underground', 'Подземная'), ('closed', 'Закрытый двор'), ('barrier', 'Шлагбаум'), ('none', 'Нет парковки')], default='none', max_length=20, null=True, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price_type',
            field=models.CharField(blank=True, choices=[('total', 'За всё'), ('sq_meter', 'За кв. метр'), ('daily', 'За сутки'), ('monthly', 'За месяц')], max_length=20, null=True, verbose_name='Тип цены'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='renovation',
            field=models.CharField(blank=True, choices=[('none', 'Без ремонта'), ('need_repair', 'Требует ремонта'), ('cosmetic', 'Косметический'), ('euro', 'Евроремонт'), ('designer', 'Дизайнерский')], max_length=20, null=True, verbose_name='Ремонт'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('active', 'Активно'), ('sold', 'Продано/Сдано'), ('rejected', 'Отклонено'), ('archive', 'Архив')], default='draft', max_length=20, null=True, verbose_name='Статус объявления'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этажность дома'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='utilities_included',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Коммунальные платежи включены'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='wall_material',
            field=models.CharField(blank=True, choices=[('brick', 'Кирпичный'), ('panel', 'Панельный'), ('monolith', 'Монолитный'), ('block', 'Блочный'), ('wood', 'Деревянный')], max_length=20, null=True, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название удобства'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, related_name='properties', to='apartnemt.amenity', verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='apartnemt.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square_meters',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая площадь (кв.м.)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartments/', verbose_name='Фотография')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartnemt.apartment', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Фотография объекта',
                'verbose_name_plural': 'Фотографии объектов',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='apartnemt.city', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название района')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='apartnemt.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='apartnemt.district', verbose_name='Район / Микрорайон'),
        ),
    ]
